<?php
use Framework\Tools\Helper\RoutesHelper;
?>

<section class="l-content content">
    <section class="home">
        <section class="home__wrapper">
            <section class="home__carousel">
            </section>

            <section class="home__post__wrapper">

            <article class="post_thumbnail">
                    <section class="post_thumbnail__wrapper">
                        <section class="post_thumbnail__image">
                            <img src="https://picsum.photos/1000/300"/>
                        </section>
                        <section class="post_thumbnail__info">
                            <section class="post_thumbnail__info__avatar">
                                <img src="https://scontent-cdt1-1.xx.fbcdn.net/v/t31.0-8/175674_1723791466115_1048654_o.jpg?_nc_cat=110&_nc_sid=09cbfe&_nc_ohc=14aBfydzFUYAX8I_q3P&_nc_ht=scontent-cdt1-1.xx&oh=42b0a1acfd0849dcd8f2d50c5ad2bbf3&oe=5F2D915B"/>
                            </section>
                            <h1 class="post_thumbnail__info__title">Le titre de la mort !!!!!!!!!!!!!!! !!!!!!!!!!!! !!!!!!!!!!!!!! !!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!</h1>
                            <time class="post_thumbnail__info__datetime" datetime="">08/07/2020 17h30</time>
                            <p class="post_thumbnail__info__description">Cras in magna eu lectus ultrices vehicula convallis viverra ex. Pellentesque dolor arcu, dignissim egestas sapien posuere, mattis vehicula nulla. Nulla facilisi. Integer ultricies, arcu ut scelerisque vulputate, ipsum mi auctor elit, vel fringilla urna nibh id orci</p>
                        </section>
                    </section>
                </article>

                <article class="post_thumbnail">
                    <section class="post_thumbnail__wrapper">
                        <section class="post_thumbnail__image">
                            <img src="https://picsum.photos/1000/300"/>
                        </section>
                        <section class="post_thumbnail__info">
                            <section class="post_thumbnail__info__avatar">
                                <img src="https://scontent-cdt1-1.xx.fbcdn.net/v/t31.0-8/175674_1723791466115_1048654_o.jpg?_nc_cat=110&_nc_sid=09cbfe&_nc_ohc=14aBfydzFUYAX8I_q3P&_nc_ht=scontent-cdt1-1.xx&oh=42b0a1acfd0849dcd8f2d50c5ad2bbf3&oe=5F2D915B"/>
                            </section>
                            <h1 class="post_thumbnail__info__title">Le titre de la mort !</h1>
                            <time class="post_thumbnail__info__datetime" datetime="">08/07/2020 17h30</time>
                            <p class="post_thumbnail__info__description">Cras in magna eu lectus ultrices vehicula convallis viverra ex. Pellentesque dolor arcu, dignissim egestas sapien posuere, mattis vehicula nulla. Nulla facilisi. Integer ultricies, arcu ut scelerisque vulputate, ipsum mi auctor elit, vel fringilla urna nibh id orci</p>
                        </section>
                    </section>
                </article>

                <article class="post_thumbnail">
                    <section class="post_thumbnail__wrapper">
                        <section class="post_thumbnail__image">
                            <img src="https://picsum.photos/1000/300"/>
                        </section>
                        <section class="post_thumbnail__info">
                            <section class="post_thumbnail__info__avatar">
                                <img src="https://scontent-cdt1-1.xx.fbcdn.net/v/t31.0-8/175674_1723791466115_1048654_o.jpg?_nc_cat=110&_nc_sid=09cbfe&_nc_ohc=14aBfydzFUYAX8I_q3P&_nc_ht=scontent-cdt1-1.xx&oh=42b0a1acfd0849dcd8f2d50c5ad2bbf3&oe=5F2D915B"/>
                            </section>
                            <h1 class="post_thumbnail__info__title">Le titre de la mort !</h1>
                            <time class="post_thumbnail__info__datetime" datetime="">08/07/2020 17h30</time>
                            <p class="post_thumbnail__info__description">Cras in magna eu lectus ultrices vehicula convallis viverra ex. Pellentesque dolor arcu, dignissim egestas sapien posuere, mattis vehicula nulla. Nulla facilisi. Integer ultricies, arcu ut scelerisque vulputate, ipsum mi auctor elit, vel fringilla urna nibh id orci</p>
                        </section>
                    </section>
                </article>

            </section>
        </section>
    </section>
</section>