<?php
use Framework\Tools\Helper\RoutesHelper;

$user = $params["User"];

$password = $params["Password"];

$violations = $params["Violations"];
$hasLoginErrors = $violations->HasErrors("Login");
$hasPasswordErrors = $violations->HasErrors("Password");
?>

<section class="l-content content">
    <section class="login">
        <h1 class="login__title">Connectez-vous !</h1>

        <section class="login__wrapper">   
            <form method="POST" action="<?= RoutesHelper::Path("UserLoginAdmin"); ?>">
                <div class="login__inputs-wrapper">
                    <div class="login__inputs-wrapper__input">
                        <div id="input-login" class="input input-login <?php if ($hasLoginErrors) echo "error"; ?>">
                            <input type="text" id="login" name="login" value="<?= $user->GetLogin(); ?>" placeholder="Identifiant" required autofocus>
                        </div>
<?php if ($hasLoginErrors): ?>
                        <section id="input-login-errors" class="error-text-wrapper">
    <?php foreach ($violations->GetErrors("Login") as $error): ?>
                            <p><?= $error; ?></p>
    <?php endforeach; ?>
                        </section>
<?php endif; ?>
                    </div>

                    <div class="login__inputs-wrapper__input">
                        <div id="input-password" class="input input-password <?php if ($hasPasswordErrors) echo "error"; ?>">
                            <input type="password" id="password" name="password" value="<?= $password; ?>" placeholder="Mot de passe" required>
                        </div>
<?php if ($hasPasswordErrors): ?>
                        <section id="input-password-errors" class="error-text-wrapper">
    <?php foreach ($violations->GetErrors("Password") as $error): ?>
                            <p><?= $error; ?></p>
    <?php endforeach; ?>
                        </section>
<?php endif; ?>
                    </div>
                </div>

                <div class="login__buttons-wrapper">
                    <button id="login-button" class="button contained-button" type="submit">Se connecter</button>
                </div>
            </form>
        </section>
    </section>
</section>

<script src="../Assets/js/module/user/login.js"></script>